apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: gitenter
spec:
  selector:
    matchLabels:
      app: gitenter
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: gitenter
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: redis:5.0.5
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
