apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: gitenter
    role: slave
    tier: backend
spec:
  ports:
  - port: 6379
  selector:
    app: gitenter
    role: slave
    tier: backend
