---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  data_bags_path: ../../data_bags
  environments_path: ../../environments
  roles_path: ../../roles

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
    driver:
      network:
      - ["private_network", {ip: "192.168.33.7"}]

suites:
  - name: default
    run_list:
      - recipe[iptables::default]
      - recipe[tomcat_init::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
