package com.gitenter.protease.dao.auth;

import java.util.List;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;

import com.gitenter.protease.domain.auth.OrganizationMemberMapBean;
import com.gitenter.protease.domain.auth.OrganizationMemberRole;

public interface OrganizationMemberMapRepository extends CrudRepository<OrganizationMemberMapBean, Integer>, OrganizationMemberMapSql {
	
	/*
	 * TODO:
	 * 
	 * By checking the SQL generated by this query, (as both member and organization
	 * are EAGER), Hibernate is not smart enough to user the JOIN query to fill all
	 * three objects. Rather, it need to do three queries, first the JOIN one, and then
	 * two other queries to get MemberBean and OrganizationBean seperately from their
	 * IDs.
	 * 
	 * Wonder if there is any way to optimize it.
	 */
	@Query("select om"
			+ " from OrganizationMemberMapBean om"
			+ " join om.organization og"
			+ " join om.member mb"
			+ " where"
			+ " og.id = :organizationId"
			+ " and mb.username = :username"
			+ " and om.role = :role")
	public List<OrganizationMemberMapBean> findByUsernameAndOrganizationIdAndRole(
			@Param("username") String username,
			@Param("organizationId") Integer organizationId,
			@Param("role") OrganizationMemberRole role);
	
	/*
	 * There is a Spring Data method "deleteById" doing the same thing.
	 * However, the problem for that is Hibernate is too smart to not
	 * doing any actual SQL query. Since "OrganizationMemberMap" is a
	 * modified @ManyToMany relation linking table, with double-link
	 * on both side, it seems extremely hard to cheat Hibernate to let 
	 * him know that this SQL should be executed (I tried to remove the
	 * link on both "MemberBean" and "OrganizationBean" side, but it is
	 * just not working).
	 * 
	 * Therefore, the current method I use is to directly generate SQL
	 * query so for sure it will be executed.
	 */
	public int throughSqldeleteById(Integer mapId);

	public OrganizationMemberMapBean saveAndFlush(OrganizationMemberMapBean map);
}
