#!/bin/sh

echo "====post-receive hook===="

# Since current directory is the root of the corresponding
# git repository (rather than inside of the "/hooks" folder)
# executing the ".jar" file will need to navigate into 
# "/hooks".
#
# To check, using
echo "current directory:" 
echo $PWD

echo "----arguments----"
echo "arg1:" $1
echo "arg2:" $2
echo "arg3:" $3

# for each ref to be updated it receives on standard input a line of the format
echo "----stdin----"
while read LINE; do
	echo ${LINE}
	java -jar hooks/postreceive-0.0.1-prototype-jar-with-dependencies.jar ${LINE}    # do something with it here
done

# A post-receive example at:
# https://github.com/git/git/blob/master/contrib/hooks/post-receive-email

