#!/bin/sh

echo "====post-update hook===="

# Since current directory is the root of the corresponding
# git repository (rather than inside of the "/hooks" folder)
# executing the ".jar" file will need to navigate into 
# "/hooks".
#
# To check, using
echo "current directory:" 
echo $PWD

# refer to https://git-scm.com/docs/githooks
# $1 is the name of the ref being updated
echo "----arguments----"
echo "arg1:" $1

# no stdin
