#!/bin/sh

echo "====post-receive hook===="

# Since current directory is the root of the corresponding
# git repository (rather than inside of the "/hooks" folder)
# executing the ".jar" file will need to navigate into 
# "/hooks".
#
# To check, using
echo "current directory:" $PWD

echo "arg1:" $1
echo "arg2:" $2
echo "arg3:" $3


