#!/bin/sh

echo "====pre-receive hook===="

# Since current directory is the root of the corresponding
# git repository (rather than inside of the "/hooks" folder)
# executing the ".jar" file will need to navigate into 
# "/hooks".
#
# To check, using
echo "current directory:" 
echo $PWD

echo "----arguments----"
echo "arg1:" $1
echo "arg2:" $2
echo "arg3:" $3

# for each ref to be updated it receives on standard input a line of the format
echo "----stdin----"
while read LINE; do
   echo ${LINE}    # do something with it here
done
