#!/bin/sh

echo "====pre-receive hook===="

# Since current directory is the root of the corresponding
# git repository (rather than inside of the "/hooks" folder)
# executing the ".jar" file will need to navigate into 
# "/hooks".
#
# To check, using
echo "current directory:" 
echo $PWD

# no argument

# refer to https://git-scm.com/docs/githooks
# for each ref to be updated it receives on standard input a line of the format
# <old-value> SP <new-value> SP <ref-name> LF
echo "----stdin----"
while read LINE; do
	echo ${LINE}
	java -jar hooks/postreceive-0.0.1-prototype-jar-with-dependencies.jar ${LINE}    # do something with it here
done
