#!/bin/sh

# Test variables
#refname="$1"
#oldrev="$2"
#newrev="$3"

#echo "refname:" $refname
#echo "oldrev:" $oldrev
#echo "newrev:" $newrev

# Since current directory is the root of the corresponding
# git repository (rather than inside of the "/hooks" folder)
# executing the ".jar" file will need to navigate into 
# "/hooks".
#
# To check, using
echo "current directory:" $PWD
java -jar hooks/update-0.0.1-prototype-jar-with-dependencies.jar $1 $2 $3

