#!/bin/sh

echo "====update hook===="

# Since current directory is the root of the corresponding
# git repository (rather than inside of the "/hooks" folder)
# executing the ".jar" file will need to navigate into 
# "/hooks".
#
# To check, using
echo "current directory:" 
echo $PWD

# refer to https://git-scm.com/docs/githooks
# $1 is the name of the ref being updated,
# $2 is the old object name stored in the ref,
# $3 is the new object name to be stored in the ref.
echo "----arguments----"
echo "arg1:" $1
echo "arg2:" $2
echo "arg3:" $3

# no stdin

# Test variables
#refname="$1"
#oldrev="$2"
#newrev="$3"

#echo "refname:" $refname
#echo "oldrev:" $oldrev
#echo "newrev:" $newrev

#java -jar hooks/update-0.0.1-prototype-jar-with-dependencies.jar $1 $2 $3

