# frozen_string_literal: true
source 'https://supermarket.chef.io'

metadata

# TODO:
# How do we use dependency so we don't need to cascadely
# import all dependent cookbooks we need?
cookbook 'postgresql'
cookbook 'iptables'

cookbook 'git_server', path:'../git_server'
cookbook 'postgres_init', path:'../postgres_init'
cookbook 'tomcat_init', path:'../tomcat_init'
